#!/usr/bin/env python3
"""Post (or update) a verdict-audit PR comment with GitHub deep links.

Called from action.yml as the comment step. Reads the scorecard from
``$REPORT``, builds a markdown body with one bullet per finding linked
to ``github.com/$REPO/blob/$HEAD_SHA/<file>#L<line>``, and either edits
an existing verdict comment (matched by a hidden HTML marker) or
creates a new one via the ``gh`` CLI.

Env in:
    REPO        owner/name          (e.g. nshah271/verdict)
    PR_NUMBER   PR number to comment on
    HEAD_SHA    full sha of the PR head commit
    REPORT      path to verdict-report.json
    GH_TOKEN    set in the caller; gh CLI reads it automatically
"""

import json
import os
import subprocess
import sys
import tempfile
from collections import Counter
from pathlib import Path


MARKER = "<!-- verdict-audit-comment -->"
MAX_FINDINGS_IN_COMMENT = 60


def _emoji(verdict: str) -> str:
    return {"PASS": "✅", "SUSPICIOUS": "🟡", "LIED": "❌"}.get(verdict, "")


def _conf_badge(conf: float) -> str:
    if conf > 0.8:
        return "🔴"
    if conf >= 0.5:
        return "🟡"
    return "🟢"


def _build_body(scorecard: dict, repo: str, sha: str, run_url: str | None) -> str:
    verdict = scorecard.get("verdict", "PASS")
    findings = scorecard.get("findings") or []
    summary = scorecard.get("summary") or {}

    lines: list[str] = [MARKER, ""]
    lines.append(f"## {_emoji(verdict)} Verdict: **{verdict}**")
    lines.append("")
    lines.append(
        f"**{summary.get('total_findings', len(findings))} findings** "
        f"from {summary.get('checks_run', '?')} checks "
        f"on `{summary.get('diff_range', '?')}`."
    )
    lines.append("")

    if not findings:
        lines.append("_No findings. Diff is clean._")
    else:
        kind_counts = Counter(f["kind"] for f in findings)
        lines.append("### By check")
        for kind, n in kind_counts.most_common():
            lines.append(f"- `{kind}`: {n}")
        lines.append("")

        lines.append("### Findings")
        shown = findings[:MAX_FINDINGS_IN_COMMENT]
        for f in shown:
            file_path = f.get("file", "") or ""
            line_no = f.get("line", 0) or 0
            conf = float(f.get("confidence", 0.0))
            msg = f.get("message", "")
            if file_path:
                url = f"https://github.com/{repo}/blob/{sha}/{file_path}#L{line_no}"
                loc = f"[`{file_path}:{line_no}`]({url})"
            else:
                loc = "_(no location)_"
            lines.append(
                f"- {_conf_badge(conf)} {loc} - {msg} `(conf: {conf:.2f})`"
            )
        if len(findings) > MAX_FINDINGS_IN_COMMENT:
            extra = len(findings) - MAX_FINDINGS_IN_COMMENT
            link = f" (see [full run log]({run_url}))" if run_url else ""
            lines.append("")
            lines.append(f"_...and {extra} more findings{link}._")

    lines.append("")
    lines.append("---")
    footer = f"_Generated by [verdict](https://github.com/{repo}) on `{sha[:7]}`._"
    if run_url:
        footer = f"_Generated by [verdict](https://github.com/{repo}) on `{sha[:7]}` ([run]({run_url}))._"
    lines.append(footer)

    return "\n".join(lines)


def _find_existing_comment_ids(repo: str, pr: str) -> list[str]:
    """List ids of existing verdict-audit comments on the PR."""
    try:
        result = subprocess.run(
            [
                "gh", "api", "--paginate",
                f"repos/{repo}/issues/{pr}/comments",
                "--jq", f'.[] | select(.body | startswith("{MARKER}")) | .id',
            ],
            capture_output=True, text=True, check=True,
        )
    except subprocess.CalledProcessError as e:
        print(f"gh api comments list failed: {e.stderr}", file=sys.stderr)
        return []
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def _patch_comment(repo: str, cid: str, body: str) -> None:
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as f:
        json.dump({"body": body}, f)
        payload = f.name
    try:
        subprocess.run(
            [
                "gh", "api",
                f"repos/{repo}/issues/comments/{cid}",
                "--method", "PATCH",
                "--input", payload,
            ],
            check=True, capture_output=True, text=True,
        )
    finally:
        os.unlink(payload)


def _delete_comment(repo: str, cid: str) -> None:
    subprocess.run(
        ["gh", "api", f"repos/{repo}/issues/comments/{cid}", "--method", "DELETE"],
        check=True, capture_output=True, text=True,
    )


def _create_comment(pr: str, body: str) -> None:
    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False) as f:
        f.write(body)
        body_file = f.name
    try:
        subprocess.run(
            ["gh", "pr", "comment", pr, "--body-file", body_file],
            check=True, capture_output=True, text=True,
        )
    finally:
        os.unlink(body_file)


def main() -> int:
    repo = os.environ.get("REPO")
    pr = os.environ.get("PR_NUMBER")
    sha = os.environ.get("HEAD_SHA", "")
    report_path = os.environ.get("REPORT")
    run_url = os.environ.get("RUN_URL") or None

    if not (repo and pr and report_path):
        print("missing REPO / PR_NUMBER / REPORT env; skipping comment.", file=sys.stderr)
        return 0

    if not Path(report_path).exists():
        print(f"report not found at {report_path}; skipping comment.", file=sys.stderr)
        return 0

    scorecard = json.loads(Path(report_path).read_text())
    body = _build_body(scorecard, repo, sha, run_url)

    existing = _find_existing_comment_ids(repo, pr)
    if existing:
        primary = existing[0]
        try:
            _patch_comment(repo, primary, body)
            print(f"updated verdict comment {primary}")
        except subprocess.CalledProcessError as e:
            print(f"PATCH failed ({e.stderr}); creating a new comment instead.", file=sys.stderr)
            _create_comment(pr, body)
        # Clean up duplicates from prior buggy runs
        for extra in existing[1:]:
            try:
                _delete_comment(repo, extra)
            except subprocess.CalledProcessError:
                pass
    else:
        _create_comment(pr, body)
        print("created new verdict comment")

    return 0


if __name__ == "__main__":
    sys.exit(main())
